<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>PerfLab.Bench</RootNamespace>
    <AssemblyName>perflab-bench</AssemblyName>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../PerfLab.Results/PerfLab.Results.csproj" />
  </ItemGroup>

</Project>
